/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package katasmain;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Clear.setOpaque(false);
        //Clear.setContentAreaFilled(false);
        //Clear.setBorderPainted(false);
        
        Login1.setOpaque(false);
        //Login1.setContentAreaFilled(false);
        //Login1.setBorderPainted(false);
        
        registerButton.setOpaque(false);
        //registerButton.setContentAreaFilled(false);
        //registerButton.setBorderPainted(false);
    }
    
    Connection Con;
    Statement St;
    ResultSet Rs;
    PreparedStatement Pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/userpass", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Product123.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Product123.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        katas = new javax.swing.JPanel();
        droplet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();
        Password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        Login1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 255, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));
        jPanel1.setLayout(null);

        katas.setBackground(new java.awt.Color(200, 234, 211));

        droplet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katasmain/droplet_export.png"))); // NOI18N
        droplet.setLabelFor(droplet);

        javax.swing.GroupLayout katasLayout = new javax.swing.GroupLayout(katas);
        katas.setLayout(katasLayout);
        katasLayout.setHorizontalGroup(
            katasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(katasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(droplet)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        katasLayout.setVerticalGroup(
            katasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(katasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(droplet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(katas);
        katas.setBounds(0, 0, 870, 60);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("USERNAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(29, 185, 130, 40);

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jLabel3.setText("No Account?");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 400, 110, 50);

        Username.setToolTipText("");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username);
        Username.setBounds(167, 185, 178, 42);

        registerButton.setBackground(new java.awt.Color(200, 234, 211));
        registerButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katasmain/register-export.png"))); // NOI18N
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton);
        registerButton.setBounds(180, 400, 160, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katasmain/water splash11.png"))); // NOI18N
        bg.setLabelFor(bg);
        bg.setPreferredSize(new java.awt.Dimension(1280, 800));
        jPanel1.add(bg);
        bg.setBounds(460, 60, 316, 410);

        Clear.setBackground(new java.awt.Color(200, 234, 211));
        Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katasmain/clear-export.png"))); // NOI18N
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(180, 340, 160, 50);

        showPassword.setBackground(new java.awt.Color(207, 255, 229));
        showPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        showPassword.setText("Show Password");
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPasswordMouseClicked(evt);
            }
        });
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword);
        showPassword.setBounds(200, 309, 110, 20);
        jPanel1.add(Password);
        Password.setBounds(167, 254, 178, 40);

        jLabel6.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel6.setText("LOGIN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 120, 100, 39);

        Login1.setBackground(new java.awt.Color(200, 234, 211));
        Login1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/katasmain/login-export.png"))); // NOI18N
        Login1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login1MouseClicked(evt);
            }
        });
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        jPanel1.add(Login1);
        Login1.setBounds(10, 340, 160, 50);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(29, 254, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        
    }//GEN-LAST:event_ClearActionPerformed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerButtonMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked

        Username.setText("");
        Password.setText("");
    }//GEN-LAST:event_ClearMouseClicked

    private void showPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMouseClicked
        if (evt.getSource() == showPassword) {
            if (showPassword.isSelected()) {
                Password.setEchoChar((char) 0);
            }
            else {
                Password.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_showPasswordMouseClicked

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPasswordActionPerformed

    private void Login1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login1MouseClicked
        String userName = Username.getText();
        
        if(Username.getText().isEmpty()||Password.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        } else {
        String Query = "select * from userpass1 where username= '"+Username.getText()+"' and password='"+Password.getText()+"'";        
        try {
            Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/userpass", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            Connect();
            if(Rs.next()) {
                
                JOptionPane.showMessageDialog(this, "Welcome " + userName);
                new Product123().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Wrong username or password");
            }
        }
            catch(Exception e) 
            {
            e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Login1MouseClicked

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Login1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel droplet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel katas;
    private javax.swing.JButton registerButton;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables

    private static class DriverManager {

        public DriverManager() {
        }
    }
}
